export interface Country {
  name: string;
  code: string; // Two-letter code
}

export const countries: Country[] = [
  
  { name: 'Andorra', code: 'AD' },
  { name: 'United Arab Emirates', code: 'AE' },
  { name: 'Afghanistan', code: 'AF' },
  { name: 'Antigua and Barbuda', code: 'AG' },
  { name: 'Anguilla', code: 'AI' },
  { name: 'Albania', code: 'AL' },
  { name: 'Armenia', code: 'AM' },
  { name: 'Angola', code: 'AO' },
  { name: 'Antarctica', code: 'AQ' },
  { name: 'Argentina', code: 'AR' },
  { name: 'American Samoa', code: 'AS' },
  { name: 'Austria', code: 'AT' },
  { name: 'Australia', code: 'AU' },
  { name: 'Aruba', code: 'AW' },
  { name: 'Åland Islands', code: 'AX' },
  { name: 'Azerbaijan', code: 'AZ' },
  { name: 'Bosnia and Herzegovina', code: 'BA' },
  { name: 'Barbados', code: 'BB' },
  { name: 'Bangladesh', code: 'BD' },
  { name: 'Belgium', code: 'BE' },
  { name: 'Burkina Faso', code: 'BF' },
  { name: 'Bulgaria', code: 'BG' },
  { name: 'Bahrain', code: 'BH' },
  { name: 'Burundi', code: 'BI' },
  { name: 'Benin', code: 'BJ' },
  { name: 'Saint Barthélemy', code: 'BL' },
  { name: 'Bermuda', code: 'BM' },
  { name: 'Brunei Darussalam', code: 'BN' },
  { name: 'Bolivia', code: 'BO' },
  { name: 'Brazil', code: 'BR' },
  { name: 'Bahamas', code: 'BS' },
  { name: 'Bhutan', code: 'BT' },
  { name: 'Botswana', code: 'BW' },
  { name: 'Belarus', code: 'BY' },
  { name: 'Belize', code: 'BZ' },
  { name: 'Canada', code: 'CA' },
  { name: 'Switzerland', code: 'CH' },
  { name: 'Chile', code: 'CL' },
  { name: 'China', code: 'CN' },
  { name: 'Colombia', code: 'CO' },
  { name: 'Costa Rica', code: 'CR' },
  { name: 'Cuba', code: 'CU' },
  { name: 'Cyprus', code: 'CY' },
  { name: 'Czechia', code: 'CZ' },
  { name: 'Germany', code: 'DE' },
  { name: 'Denmark', code: 'DK' },
  { name: 'Dominica', code: 'DM' },
  { name: 'Dominican Republic', code: 'DO' },
  { name: 'Algeria', code: 'DZ' },
  { name: 'Ecuador', code: 'EC' },
  { name: 'Estonia', code: 'EE' },
  { name: 'Egypt', code: 'EG' },
  { name: 'Spain', code: 'ES' },
  { name: 'Ethiopia', code: 'ET' },
  { name: 'Finland', code: 'FI' },
  { name: 'Fiji', code: 'FJ' },
  { name: 'France', code: 'FR' },
  { name: 'United Kingdom', code: 'GB' },
  { name: 'Georgia', code: 'GE' },
  { name: 'Ghana', code: 'GH' },
  { name: 'Greenland', code: 'GL' },
  { name: 'Gambia', code: 'GM' },
  { name: 'Guinea', code: 'GN' },
  { name: 'Greece', code: 'GR' },
  { name: 'Guatemala', code: 'GT' },
  { name: 'Guam', code: 'GU' },
  { name: 'Hong Kong', code: 'HK' },
  { name: 'Honduras', code: 'HN' },
  { name: 'Croatia', code: 'HR' },
  { name: 'Haiti', code: 'HT' },
  { name: 'Hungary', code: 'HU' },
  { name: 'Ireland', code: 'IE' },
  { name: 'Israel', code: 'IL' },
  { name: 'India', code: 'IN' },
  { name: 'Iraq', code: 'IQ' },
  { name: 'Iran', code: 'IR' },
  { name: 'Indonesia', code: 'ID' },
  { name: 'Iceland', code: 'IS' },
  { name: 'Italy', code: 'IT' },
  { name: 'Jamaica', code: 'JM' },
  { name: 'Jordan', code: 'JO' },
  { name: 'Japan', code: 'JP' },
  { name: 'Kenya', code: 'KE' },
  { name: 'Kyrgyzstan', code: 'KG' },
  { name: 'Cambodia', code: 'KH' },
  { name: 'Kiribati', code: 'KI' },
  { name: 'South Korea', code: 'KR' },
  { name: 'Kuwait', code: 'KW' },
  { name: 'Kazakhstan', code: 'KZ' },
  { name: 'Laos', code: 'LA' },
  { name: 'Lebanon', code: 'LB' },
  { name: 'Sri Lanka', code: 'LK' },
  { name: 'Lithuania', code: 'LT' },
  { name: 'Luxembourg', code: 'LU' },
  { name: 'Latvia', code: 'LV' },
  { name: 'Libya', code: 'LY' },
  { name: 'Morocco', code: 'MA' },
  { name: 'Monaco', code: 'MC' },
  { name: 'Moldova', code: 'MD' },
  { name: 'Madagascar', code: 'MG' },
  { name: 'Macedonia', code: 'MK' },
  { name: 'Mali', code: 'ML' },
  { name: 'Myanmar', code: 'MM' },
  { name: 'Mongolia', code: 'MN' },
  { name: 'Macao', code: 'MO' },
  { name: 'Mauritania', code: 'MR' },
  { name: 'Malta', code: 'MT' },
  { name: 'Mauritius', code: 'MU' },
  { name: 'Maldives', code: 'MV' },
  { name: 'Malawi', code: 'MW' },
  { name: 'Mexico', code: 'MX' },
  { name: 'Malaysia', code: 'MY' },
  { name: 'Mozambique', code: 'MZ' },
  { name: 'Namibia', code: 'NA' },
  { name: 'Niger', code: 'NE' },
  { name: 'Nigeria', code: 'NG' },
  { name: 'Nicaragua', code: 'NI' },
  { name: 'Netherlands', code: 'NL' },
  { name: 'Norway', code: 'NO' },
  { name: 'Nepal', code: 'NP' },
  { name: 'New Zealand', code: 'NZ' },
  { name: 'Oman', code: 'OM' },
  { name: 'Panama', code: 'PA' },
  { name: 'Peru', code: 'PE' },
  { name: 'Philippines', code: 'PH' },
  { name: 'Pakistan', code: 'PK' },
  { name: 'Poland', code: 'PL' },
  { name: 'Puerto Rico', code: 'PR' },
  { name: 'Portugal', code: 'PT' },
  { name: 'Paraguay', code: 'PY' },
  { name: 'Qatar', code: 'QA' },
  { name: 'Romania', code: 'RO' },
  { name: 'Serbia', code: 'RS' },
  { name: 'Russia', code: 'RU' },
  { name: 'Rwanda', code: 'RW' },
  { name: 'Saudi Arabia', code: 'SA' },
  { name: 'Sudan', code: 'SD' },
  { name: 'Sweden', code: 'SE' },
  { name: 'Singapore', code: 'SG' },
  { name: 'Slovenia', code: 'SI' },
  { name: 'Slovakia', code: 'SK' },
  { name: 'Senegal', code: 'SN' },
  { name: 'Somalia', code: 'SO' },
  { name: 'Suriname', code: 'SR' },
  { name: 'El Salvador', code: 'SV' },
  { name: 'Syria', code: 'SY' },
  { name: 'Swaziland', code: 'SZ' },
  { name: 'Chad', code: 'TD' },
  { name: 'Togo', code: 'TG' },
  { name: 'Thailand', code: 'TH' },
  { name: 'Tajikistan', code: 'TJ' },
  { name: 'Timor-Leste', code: 'TL' },
  { name: 'Turkmenistan', code: 'TM' },
  { name: 'Tunisia', code: 'TN' },
  { name: 'Tonga', code: 'TO' },
  { name: 'Turkey', code: 'TR' },
  { name: 'Taiwan', code: 'TW' },
  { name: 'Tanzania', code: 'TZ' },
  { name: 'Ukraine', code: 'UA' },
  { name: 'Uganda', code: 'UG' },
  { name: 'United States', code: 'US' },
  { name: 'Uruguay', code: 'UY' },
  { name: 'Uzbekistan', code: 'UZ' },
  { name: 'Vatican', code: 'VA' },
  { name: 'Venezuela', code: 'VE' },
  { name: 'Vietnam', code: 'VN' },
  { name: 'Samoa', code: 'WS' },
  { name: 'Yemen', code: 'YE' },
  { name: 'South Africa', code: 'ZA' },
  { name: 'Zambia', code: 'ZM' },
  { name: 'Zimbabwe', code: 'ZW' },
];

export function getCountryByCode(code: string): string {
  return countries.find(c => c.code === code)?.name || code;
}
